### PR TITLE
fix: dark mode validations

### PR DESCRIPTION
**Pull request by mallachari**
Needed for: https://github.com/stoplightio/elements/issues/1149

Makes validations values support dark mode

Screenshot from 2021-05-31 13-06-51

### CODE REVIEW

**Review by mpodlasin — COMMENTED** [review]
I know that @marcelltoth was removing some mosaic elements from JSV to reduce render times.

Maybe you two can collaborate to test if/how this change affects performance?

Unless @marcelltoth believes that it will be a non-issue here of course :)

**Comment by marcelltoth** [comment]
> I know that @marcelltoth was removing some mosaic elements from JSV to reduce render times.
> 
> Maybe you two can collaborate to test if/how this change affects performance?

That was my only worrying thought as well. 😄 Let's see how the stress schema renders. Maybe it's not that bad as it's only validations. 🤔

**Comment by mallachari** [comment]
> > I know that @marcelltoth was removing some mosaic elements from JSV to reduce render times.
> > Maybe you two can collaborate to test if/how this change affects performance?
> 
> That was my only worrying thought as well.  Let's see how the stress schema renders. Maybe it's not that bad as it's only validations.

Well, it seems to render fine from what I can see. I added those mosaic components by the way, so we can keep it the way it was, just use it for validations where it's necessary.

**Review by marcelltoth — APPROVED** [review]
I did a rough measurement now. It's worse, but not horrible, around ~5-10%. I'm OK with it if you are.

**Pull request merged**
