### PR TITLE
STOP-1012(Bump): semver version updated for security issues

### PR DESCRIPTION
**Pull request by SB-rohitdesai**
## Motivation and Context

#STOP-1012

## Description

A vulnerability was detected within the json-schema-viewer project through the inclusion of the semver dependency.
Semver is internally used by @size-limit/preset-big-lib this package. to resolve this dependency we updated @size-limit/preset-big-lib package.

## How Has This Been Tested?
1. Locally tested , test cases , build and code also running and working properly
2. Yalc the change into platform-internal and tested 

## Screenshot(s)/recordings(s)

image
image
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] This PR's code follows as closely as possible [the coding style/guidelines of this project](???).
- [ ] I have added error reporting and followed [the error reporting guidelines](???).
- [ ] I have added event tracking and followed [the event tracking guidelines](???).
- [ ] I have updated any relevant documentation accordingly to reflect this PR's changes.
- [ ] I have added automated tests (unit/integration/e2e/other) to cover my changes.
- [ ] All new and existing tests pass locally (excluding flaky CI tests).

### CODE REVIEW

**Comment by bhaskarsontakke** [comment]
@SB-rohitdesai  please yalc the json-schema-viewer and test in platform-internal. Make sure you cover all the places where JSON-SCHEMA-VIEWER is used. Also, run the all the test cases.

**Comment by SB-rohitdesai** [comment]
> @SB-rohitdesai please yalc the json-schema-viewer and test in platform-internal. Make sure you cover all the places where JSON-SCHEMA-VIEWER is used. Also, run the all the test cases.

Done

**Review by prafullaAtSB — APPROVED** [review]
Looks good on devDependences front. 
Go ahead. Check with other products using yalc

**Comment by SB-rohitdesai** [comment]
> Looks good on devDependences front. Go ahead. Check with other products using yalc

Yes , checked with other repo's

**Pull request merged**
