### PR TITLE
feat: masking [STU-18]

### PR DESCRIPTION
**Pull request by P0lip**

### CODE REVIEW

**Comment by wmhilton** [comment]
The jira story is empty. What's the TL;DR for "masking"? I know it was mentioned in that one big doc but I can't remember how to find it.

**Comment by wmhilton** [comment]
A.... a modal popup dialog? How about we add a `showMasks` prop and add a column, like in the screenshots?

**Comment by P0lip** [comment]
> How about we add a showMasks prop and add a column, like in the screenshots?

Which screenshots?
The idea of popup and edit mask button was said during the meet I had with Brian and Marc.
I'll ask them again to see what the actual plan is.

**Comment by wmhilton** [comment]
I was looking a this one:
image

I mean... I'm fine with a Popup as long as I never have to use the feature myself... chortle.

**Comment by P0lip** [comment]
The above is JSE editor though and I guess it's just mean to say "hey, don't display that property/line".

**Comment by P0lip** [comment]
I'll address any potential adjustments in a separate PR.

**Pull request merged**
