### PR TITLE
feat: better support of anyOf/oneOf + type scenario

### PR DESCRIPTION
**Pull request by P0lip**
Requires https://github.com/stoplightio/json-schema-viewer/pull/86

Closes_ https://github.com/stoplightio/platform-internal/issues/4382

### CODE REVIEW

**Comment by P0lip** [comment]
@marbemac this is very likely to break masking.
Shall we hide it behind a flag or something? Is displaying an old view acceptable for masking view?

**Comment by marbemac** [comment]
> this is very likely to break masking.

Hmm, what's the example(s) you're thinking of re what might break?

**Comment by P0lip** [comment]
Well, I'm confident the oneOf/anyOf + type scenario will be almost always broken, as property paths will be mismatched.
We'd need to perform the same kind of merging on the backend side of masking for the paths to match.

**Comment by P0lip** [comment]
I kicked of another project called [@stoplight/json-schema-tree](https://github.com/stoplightio/json-schema-tree) that is supposed to take out of all the schema processing logic we have in JSV - do note that although the logic is more or less similar, it's been vastly refactored to payback the debt we have in JSV.
We'll be able to share it between masking & jsv, and possibly JSE.
This will significantly simplify JSV making contributions much easier, in particular when it comes to plain UI changes.

**Comment by P0lip** [comment]
@stoplightio/void-crew anyone? it's ready.

**Review by marbemac — APPROVED** [review]
Nice, looks great 👏 . I think the combiner + type merging is specific enough that we roll the dice and hope that design lib folks don't use it much (probably not at all tbh, not many folks are using design libs and masking yet).

**Comment by wmhilton** [comment]
> @stoplightio/void-crew anyone? it's ready.

What do you mean by "ready" exactly? Is it still going to break masking?

**Comment by P0lip** [comment]
Yeah, it might break it at times but what Marc said. It's a rare scenario. Currently we don't display anything in such case so masking doesn't really work anyway.

**Pull request merged**
