### PR TITLE
fix(render-schema): generate correct paths

### PR DESCRIPTION
**Pull request by P0lip**

### CODE REVIEW

**Comment by chris-miaskowski** [comment]
@lag-of-death fix for the incorrect paths, please merge to your JSV and Studio

**Comment by P0lip** [comment]
@chris-miaskowski I already cherry-picked the commit onto the maskig branch :)

**Comment by lag-of-death** [comment]
@P0lip, where it was cherrypicked onto?

**Comment by chris-miaskowski** [comment]
> @P0lip, where it was cherrypicked onto?

https://github.com/stoplightio/json-schema-viewer/pull/33

**Pull request merged**
