### PR TITLE
feat: ref details popover [STU-185]

### PR DESCRIPTION
**Pull request by P0lip**
See the STU-180 story for more info.

Light theme:
Screenshot_20190521_222134
Dark theme:
Screenshot_20190521_221951

Open questions:
- is tooltip-based approach a right call?
- should we make URL a bit more flexible and allow it to be, say, a callback? it might make routing easier in the future.
- how would the Studio integration look like?

### CODE REVIEW

**Comment by lottamus** [comment]
Could just do a simple inline "(go to ref)" like we had in Next? 

Clicking "(go to ref)" could emit `JsonSchemaEditorStoreEvents.GoToRef` or something and let the consumer handle it however. 

Studio can listen to that event, look up a Model node that matches the given URI, and set it as the active node?

image

**Comment by marbemac** [comment]
I agree with @lottamus - what do you think @P0lip?

**Comment by P0lip** [comment]
@marbemac 
Already implemented in https://github.com/stoplightio/json-schema-editor/pull/24
Shall we apply the same change to JSV?

**Comment by lottamus** [comment]
> Shall we apply the same change to JSV?

Yeah I'd say so. But if we're showing a `$ref` in JSV it's likely because we couldn't resolve it so its unlikely that the `$ref` even exists

**Pull request merged**
