### PR TITLE
fix: show guideline to right props on hover if present

### PR DESCRIPTION
**Pull request by marbemac**
To help visually connect prop to extra values on right if there are any.

### CODE REVIEW

**Comment by wmhilton** [comment]
screenshot looks good! gonna try running storybook locally. I'm curious how it handles on touch screens or with keyboard focus.

**Comment by marbemac** [comment]
Good call! I'll check too

**Comment by marbemac** [comment]
So obv no hover on touch screen, but will show on tap in this case 🤷‍♂️

**Comment by marbemac** [comment]
On the other side of things, I have a whole lot of ideas re keyboard accessibility / navigation that I'd like to visit at some point.

**Comment by wmhilton** [comment]
(Keyboard accessibility is a big ask obviously, but touch support is simple enough.)

Edit: Looks like `setHoveredNode` is called when nodes are touched, so looks nice on mobile 👍🏻

**Review by wmhilton — APPROVED** [review]
Looks beautiful!

**Pull request merged**
